### PR TITLE
Make the 3D Tiles Next page to a landing page

### PR DESCRIPTION
**Pull request by ptrgags**
the `3D_TILES_NEXT.md` page is not how we usually like to store Markdown documentation. Usually we like to make a folder and have a README.md so it shows up nicer in GitHub.

@donmccurdy I did this targeting the `3d-tiles-next` branch, wasn't sure what's best for your workflow when you work on revising this document.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Moving this to a directory sounds good to me, but two quick things:

- The other top-level directories are lowercase, should we follow that convention? Maybe just `next/README.md`?
    - Screen Shot 2021-11-03 at 8 56 21 AM
- Links to images are broken in this PR. Not a big deal if there's nothing currently pointing here, I can just fix those when I do the other updates.

**Comment by ptrgags** [comment]
@donmccurdy silly me, I updated the images!

**Review by donmccurdy — APPROVED** [review]
The relative links — e.g. to extensions — are broken, but I'm happy to fix those in a writing pass. Looks good to me otherwise!

**Comment by ptrgags** [comment]
@donmccurdy I was talking to @lilleyse about this yesterday, we actually want to do this targeting `main` (now that all the specs are in `main`, we should be avoid the `3d-tiles-next` branch here since it's outdated.

I'll open a new PR shortly.

**Pull request closed without merging**
