### PR TITLE
Experiments for OGC standard template

### PR DESCRIPTION
**Pull request by javagl**
For now, this inserts only the header from the [community standard template](https://github.com/opengeospatial/templates/tree/master/community_standard). 

Assuming that you already can run "Metanorma", the command line

    metanorma compile --agree-to-terms -t ogc -x html,pdf Specification.adoc

should generate a PDF file (the HTML output is still broken...)

Build instructions will be added here or in the `BUILDING.md` soon. Fow now, I can only give the recommendation to **NOT** install Metanorma, but instead, use the Docker container. (Details of _how_ to use the Docker container to build the specs will also be added, as soon as I have figured that one out...)

A preliminary list of TODOs, derived from warnings or issues during the build process:

- Warnings that are caused by a wrong structure:
    ```
    (): Keywords are missing!
    (): Submitting Organizations is missing!
    (): Submitters is missing!
    (): Prefatory material must be followed by (clause) Scope
    (): Scope must be followed by Conformance
    (): Normative References must be followed by Terms and Definitions
    (): Normative References are mandatory
    (): Abstract is missing!
    ``` 
    Most of them should be easy to fix, by adding the sections as described in https://www.metanorma.org/author/ogc/authoring-guide/sections-ogc/ , or adding things like
    `:submitting-organizations: ...`
    to the current header in `Specification.adoc`

- Each code snippet is considered to be a 'Figure', and is listed in the 'List of Figures' ... with an empty title. There may be an option to tell Metanorma that `[source]` is not a 'Figure'...
- Each table will need a title, to be properly listed in the 'List of Tables'

- For the HTML output, there is an error message that is probably caused by the fact that images are _inlined_ as data URIs. Actually, this should _not_ be the default. There is an AsciiDoc [`:data-uri:`](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/) option to enable this, and a Metanorma [`--no-datauriimage`](https://www.metanorma.org/install/man/) CLI Option to disable it, but this does not seem to have any effect

### CODE REVIEW

**Comment by lilleyse** [comment]
@javagl the guidance document linked in https://docs.ogc.org/pol/05-020r27/05-020r27.html#main-steps-in-the-standard-process goes into more detail about the preface/scope:

> Documents being submitted as Full standards shall use the [document formatting and content](https://portal.opengeospatial.org/files/?artifact_id=56777/), in common use by the OGC at the time of submission, of standards submitted under the OGC Consensus Standards process. There is a detailed [guidance document](https://portal.opengeospatial.org/files/?artifact_id=3244/) for using the template.
> 
> Documents being submitted as Community standards do not need to follow the OGC document template for an OGC standard. However, the submission team for a Community standard is strongly encouraged to provide the candidate standard to the OGC using the document template.

You might be able to reference the 3D Tiles 1.0 submission too: https://github.com/CesiumGS/3d-tiles/blob/main/specification/specification.pdf

**Comment by javagl** [comment]
There have been some updates

1. Added "Terms And Definitions"
2. Added "References"
3. Extended "Revision History"

This is largely based on the 3D Tiles 1.0 spec from https://github.com/metanorma/mn-samples-ogc/blob/main/sources/18-053r2/ , so they may be incomplete (i.e. we should check which additional entries 1. and 2. need , and keep an eye on https://www.metanorma.org/author/ogc/authoring-guide/terms-definitions/#entering-terminology-entries ).

The Revision History is taken from 1.0 - I **assume** that this should be done, because we are in fact only updating the 1.0 specification. 

---

There have been some tweaks in the section structure, trying to minimize the number of warnings (and make sections appear properly in the TOC), but ... a "warning-free" state _might_ be an unachievable ideal. (I'm not even talking about the ~100 "Matenorma XML syntax" warnings, but the "coars-grained" ones that indicate wrong section orders, regardless of the order of the sections...)

---

A spec-lawyer detail: https://www.metanorma.org/author/ogc/topics/markup/ says

> Where section obligations are named (i.e. in annex names), they are only given as “normative” or “informative”; the alternate text of “non-normative” is disallowed.

While this only seems to refer the whole _sections_, we are declaring _inlined_ sections (implementation examples) as 'non-normative' (and use the term "Implementation Note" occasionally to declare non-normativeness). Should that be changed/reviewed?

**Comment by lilleyse** [comment]
I'm seeing a bunch of warnings from metanorma. Which of these need to be addressed and which are just noise?

```
(base) slilley@Hydrogen:~/Code/3d-tiles/specification$ docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts metanorma/metanorma metanorma compile --agree-to-terms -t ogc -x html,pdf Specification.adoc
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
[relaton] EPSG WGS-84-3 does not have a recognised prefix
[relaton] Khronos Group glTF 2.0 does not have a recognised prefix
[relaton-w3c] ("W3C css-color-3") fetching...
[relaton-ietf] ("IETF RFC 2397") fetching...
[relaton-ogc] ("OGC 12-063r5") fetching...
[relaton-ietf] ("IETF RFC 2397") found RFC 2397
[relaton-ogc] ("OGC 12-063r5") found 12-063r5
[relaton-ietf] ("IETF RFC 3629") fetching...
[relaton-w3c] ("W3C css-color-3") found css-color-3
[relaton-ietf] ("IETF RFC 3629") found RFC 3629
[relaton-ietf] ("IETF RFC 3986") fetching...
[relaton-ietf] ("IETF RFC 3986") found RFC 3986
[relaton] EPSG WGS-84-3 does not have a recognised prefix
[relaton] Khronos Group glTF 2.0 does not have a recognised prefix
Style: Preface is missing!
Metanorma XML Style Warning: (XML Line 000428): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000454): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000493): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000679): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000908): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001008): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001129): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001361): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001500): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001612): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001643): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001662): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001849): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001862): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001931): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001944): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001997): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002045): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002132): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002151): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002209): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002314): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002346): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002383): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002459): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002503): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002516): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002567): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002671): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002716): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002742): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002936): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 002951): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003122): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003261): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003277): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003365): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003414): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003808): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003831): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003874): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003927): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 004728): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 004769): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 004839): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 005201): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 005371): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006013): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006097): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006207): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006291): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006494): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006593): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006698): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006820): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 006929): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 007277): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 007395): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 007494): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 007631): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 007758): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008063): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008153): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008417): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008507): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008771): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008855): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 008979): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009196): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009250): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009414): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009489): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009581): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009761): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009905): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 009996): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 010052): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 010246): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 010326): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 010546): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 010671): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 012907): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 013125): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 013145): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 013254): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 013266): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000018): Figure should have title
Metanorma XML Style Warning: (XML Line 000018): Figure should have title
Metanorma XML Style Warning: (XML Line 000024): Table should have title
Metanorma XML Style Warning: (XML Line 003890): Table should have title
Metanorma XML Style Warning: (XML Line 003963): Table should have title
Metanorma XML Style Warning: (XML Line 003975): Table should have title
Metanorma XML Style Warning: (XML Line 004195): Table should have title
Metanorma XML Style Warning: (XML Line 004414): Table should have title
Metanorma XML Style Warning: (XML Line 004428): Table should have title
Metanorma XML Style Warning: (XML Line 013874): Table should have title
Metanorma XML Syntax: (XML Line 000140:104): element "clause" not allowed here; expected element "foreword"
Metanorma XML Syntax: (XML Line 000140:290): element "submitters" not allowed yet; missing required element "foreword"
Metanorma XML Syntax: (XML Line 000193:174): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "hi", "hr", "image", "index", "index-xref", "keyword", "link", "note", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 000236:330): element "fn" not allowed here; expected the element end-tag, text or element "add", "bookmark", "br", "concept", "del", "em", "eref", "hi", "hr", "image", "index", "index-xref", "keyword", "link", "note", "pagebreak", "ruby", "smallcap", "span", "stem", "strike", "strong", "sub", "sup", "svg", "tt", "underline" or "xref"
Metanorma XML Syntax: (XML Line 003258:47): element "p" not allowed here; expected the element end-tag
Metanorma XML Syntax: (XML Line 003456:52): element "figure" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 003956:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004031:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004043:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004263:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004411:52): element "figure" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004456:52): element "figure" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004463:52): element "figure" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004482:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 004496:51): element "table" not allowed here; expected the element end-tag or element "dl", "formula", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 014042:123): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 014076:145): element "docidentifier" not allowed yet; missing required element "title"
java -Xss5m -Xmx2048m -jar /usr/local/bundle/gems/mn2pdf-1.47/lib/../bin/mn2pdf.jar --xml-file "/metanorma/Specification.presentation.xml" --xsl-file "/usr/local/bundle/gems/metanorma-ogc-2.1.3/lib/isodoc/ogc/ogc.community-standard.xsl" --pdf-file "/metanorma/Specification.pdf" --syntax-highlight  --font-manifest "/tmp/fontist_locations20220627-1-sarrz9.yml"
```

**Comment by javagl** [comment]
As mentioned above: A "warning-free" state might be an unachievable ideal.

But to roughly categorize the messages

---

> [relaton] EPSG WGS-84-3 does not have a recognised prefix
> [relaton] Khronos Group glTF 2.0 does not have a recognised prefix

This refers to the functionality of [auto-fetching](https://www.metanorma.org/author/topics/document-format/bibliography/#named-reference-tag-with-automatic-reference-fetching) reference information for certain types of references (e.g. for ISO standard references or so). We might change the reference to use one of the "known reference repository identifiers", but I think this is mainly a convenience, compared to manually defining it.

---

> Style: Preface is missing!

We can add a section called `Preface`. I don't know what it should contain, though. The "Abstract", "Scope" and "Conformance" already felt a bit handwaving...


---

> ... element "table" not allowed here; expected ...
> ... element "figure" not allowed here; expected ...

These seem to be _mostly_ caused by the cases where we have tables and images in admonitions (i.e. in the 'Note'-blocks). Why it prints a warning for that? I don't know...

--- 

> Hanging paragraph in clause ...
> element ... not allowed here; 
> ...

🤷‍♂️

I can look at [the code/rule that generated this message](https://www.rubydoc.info/gems/metanorma-standoc/1.9.3/Asciidoctor%2FStandoc%2FValidate:hanging_para_style), and I can look at the XML to see the offenting elements, but I don't know why they are not allowed there, or where these elements come from in the first place. 

From my understanding, the approach of Metanorma, on the oversimplified level, is 

 1. Take any input (HTML, ADOC, MD, DOC, ...)
 2. Convert it into an 'XML to rule them all'
 3. Perform some sanity checks on the XML
 4. Use the XML to generate any output (HTML, PDF, DOC, ...)

Now, many things can go wrong there. I did not yet go down to the level where I'd try to debug the Ruby code that is running inside the Docker container or so. But I can investigate these warnings, on demand...

**Comment by javagl** [comment]
An aside: In the command line that is used for creating the specs, one can add
```
... -x html,pdf,xml
                ^ this
```
in order to retain this XML file that the warnings refer to.

**Comment by lilleyse** [comment]
The HTML output seems to be missing "List of Tables" and "List of Figures" (possibly a bug in the HTML generator since there's no table of contents in the HTML output?). Most likely out of our control.

**Comment by javagl** [comment]
- Condensed revision history
- Changed "Implementation Note" and "...non-normative" to "informative"
- Changed all dates and identifiers to `TBD`. (This causes warnings - they _want_ a date there)
- Updated keywords as requested
- Added 'Preface', 'Future Work', 'Conventions' - note that the section numbering (roman vs. arabic numbers) uses some internal magic - I think it just starts with the arabic `1.` at 'Scope' - and the order of the sections does not match the order in the input file...
- Wording updates for 'Conformance' section
  Note: 
  > Maybe copy it, update the sections numbers, and link to Appendix B (JSON schema reference).

  I assume that this should link to the 'Properties Reference' (or do we want to make the schema reference normative?)
- Added glTF in list of tile formats in 'Terms and Definitions'
- Updated/extended the 'References' (WKT, EPSG, JSON encoding)


---

> I took a look at OGC Policy Directive 49 - we should try to use the same language wherever possible. The biggest thing is changing "must" to "shall" everywhere.

The word 'must' appears 209 times in the specification. I can go through these and see which of them <strike>must</strike> shall be changed. But many of them appear in the properties reference, so this may rather be an issue of https://github.com/CesiumGS/wetzel/blob/82890df68ae4c24c5679196c06e3afccd6673a30/lib/style.js#L132 ...

---

An aside: Among the XML warnings is one

> element "fn" not allowed 

This is caused by footnotes. In the PDF, footnotes appear at the bottom of the page. In the HTML, they appear ... at the bottom ... of ... everything. I think we should avoid footnotes, and just use a plain link instead (there are only 2 of them).

**Review by javagl — COMMENTED** [review]
<sup>EDITED: This is obsolete as of the comment below</sup>

I'm suprised - did the 'MIME' slip back in at some point after https://github.com/CesiumGS/3d-tiles/commit/b46c42d766913e441962081d5849b5f8e9b6d823#diff-8034c95ee174226b9529fb7896346c6b53f7d421e34c78607ab0e2055f1913ce ? (I think I did a full text search for 'MIME' back then, and can hardly imagine having overlooked this...)

**Comment by javagl** [comment]
💡 this "MIME type" vs. "madia type" change was only applied to the `.MD` files. Sorry about that.

**Comment by lilleyse** [comment]
Hmm... so we can't control where the Future Work section goes? It doesn't feel right to include it in the main spec body when it really belongs in the preliminary sections. That seems to be the convention for other specs too.

**Comment by lilleyse** [comment]
> The word 'must' appears 209 times in the specification. I can go through these and see which of them <strike>must</strike> shall be changed. But many of them appear in the properties reference, so this may rather be an issue of https://github.com/CesiumGS/wetzel/blob/82890df68ae4c24c5679196c06e3afccd6673a30/lib/style.js#L132 ...

Yeah let's update all those, including the wetzel branch (and regenerate the property reference)

**Comment by javagl** [comment]
The point about wetzel: Sorry, I said something that was ... essentially wrong there. Wetzel _does_ insert the "must-keyword" at some places, but there is nothing to fix in wetzel itself - just to add `-k "shall"` to the command line.

Beyond that, most appearances of 'must' are from the `description` in the schema, so this _will_ indeed be a rather manual process.

(I can tackle that a bit later today)

**Comment by lilleyse** [comment]
> Apparently, it can be tagged as [.preface] - from https://www.metanorma.org/author/ogc/authoring-guide/sections-ogc/#ogc-additional-prelim - which is "allowed but not encouraged"...

Let's do it. Even the [OGC Standard for Modular specifications](https://portal.opengeospatial.org/files/?artifact_id=34762) includes  it in the preliminary sections.

**Comment by lilleyse** [comment]
I did a quick final pass over the HTML and PDF. I don't think there's anything left to add here. Thanks @javagl!

**Comment by javagl** [comment]
> For a moment, I thought that it might actually complain about "empty" clauses: From other standardization efforts, I know that it is sometimes considered to be problematic to have sections like ... 

Another thing that might come up in terms of ~"broad, editorial/typesetting practices" is that we often do not refer to images and tables in the text. As far as I know, patterns like

> Some data can be stored in some way.
> 
> **Some Table**
> | A      | B|
> | ----------- | ----------- |
> | X| Y|

should rather be linked, as in 

> Some data can be stored as shown in [Some Table](https://example.com)
> ...

But we'll fix that if it actually comes up.

**Comment by lilleyse** [comment]
> The code snippets are no longer counted as figures, by marking them as [%unnumbered]

@javagl did this change go back into the wetzel branch? I regenerated the property reference just now and the lines were removed.

image

**Comment by javagl** [comment]
@lilleyse It might well be that I did this manually in the rush back then, but ... doing the fix wouldn't have taken much longer, so I just opened https://github.com/CesiumGS/wetzel/pull/84 ...

**Comment by lilleyse** [comment]
Thanks @javagl

**Pull request merged**
