### PR TITLE
Fix S2 cell ID examples

### PR DESCRIPTION
**Pull request by newtonallen3**

### CODE REVIEW

**Comment by sanjeetsuhag** [comment]
@newtonallen3 Thank you for the fix! The suggested change looks correct to me. Please sign the [Cesium Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) and then I can merge this.

**Comment by newtonallen3** [comment]
Thanks. After a delay related to learning about CLAs... I'm contributing this on behalf of Google, which has already signed a corporate CLA. So I believe I don't need to sign anything further. Is that correct?

**Comment by sanjeetsuhag** [comment]
> I'm contributing this on behalf of Google, which has already signed a corporate CLA. So I believe I don't need to sign anything further. Is that correct?

Yes, you're correct. I can merge this now. Thanks again for the contribution @newtonallen3!

**Comment by newtonallen3** [comment]
Thanks!

**Pull request merged**
