### PR TITLE
Tile expiration

### PR DESCRIPTION
**Pull request by lilleyse**
For #99
Cesium implementation: https://github.com/AnalyticalGraphicsInc/cesium/pull/4136

One point I have not addressed yet is

> Time expiration should be in the tile (header / feature json) so it can change from request to request.

I wish this didn't have to happen but I can't think of another way.

Each tile's feature table could have a `TILE` object which mimics the layout of a tile in tileset.json. This will also be helpful for bounding volumes in #92 too.

### CODE REVIEW

**Comment by lilleyse** [comment]
I started some work on a `TILE_METADATA` section in the feature table. @pjcozzi do you think this is the right idea?

**Comment by pjcozzi** [comment]
> I started some work on a TILE_METADATA section in the feature table. @pjcozzi do you think this is the right idea?

I think we'll need something like this to get full mileage out of explicit tiling schemes, but we might also want it to have child tile metadata for efficient culling.

We have two options
* Push tile expiration post 1.0.  I think it can be added in a backwards compatible way and it is not yet a popular feature.
* Pseudo-design just enough of #92 to make sure we are going down the right path here.

Perhaps we wait to decide based on how fast the rest of the 1.0 work goes?

**Comment by lilleyse** [comment]
> Perhaps we wait to decide based on how fast the rest of the 1.0 work goes?

Sounds good, if expiration doesn't go in that would be ok with me.

**Comment by lilleyse** [comment]
Closing due to inactivity

**Pull request closed without merging**
