### PR TITLE
Ecosystem and resources

### PR DESCRIPTION
**Pull request by javagl**
#### Preview link: https://github.com/javagl/3d-tiles/blob/draft-1.1-resources/RESOURCES.md

<sup>(Related to https://github.com/CesiumGS/3d-tiles/issues/560)</sup>

There are currently different places that contain information that is somewhat scattered:

- The [3D Tiles Ecosystem](https://github.com/CesiumGS/3d-tiles/tree/cbab36e412c5fcb5a6a33b515ce07fbb82a9edf8#3d-tiles-ecosystem) section in the main README. It refers to CesiumJS/ion, some of the developer tools (like the validator), and ... two other applications... (?)
- The [RESOURCES.md](https://github.com/CesiumGS/3d-tiles/blob/cbab36e412c5fcb5a6a33b515ce07fbb82a9edf8/RESOURCES.md) page. It mainly contains talks/videos/blog posts, and a few links to the specification and implementations
- The [ECOSYSTEM.md](https://github.com/CesiumGS/3d-tiles/blob/cbab36e412c5fcb5a6a33b515ce07fbb82a9edf8/ECOSYSTEM.md) page. It contains a lot of screenshots + links, without any context
- There was a dedicated [RESOURCES.md for 3D Tiles Next](https://github.com/CesiumGS/3d-tiles/blob/cbab36e412c5fcb5a6a33b515ce07fbb82a9edf8/next/RESOURCES.md). This has already beed addressed insofar that this document is phased out, and its information is moved into the main RESOURCES.md.

---

The _overall_ structure of how this information will be presented is not yet decided upon. 

I just started with trying to sort the ECOSYSTEM.md. The current state can be seen at https://github.com/javagl/3d-tiles/blob/draft-1.1-resources/ECOSYSTEM.md 

<sup>(Note: this is an early draft. Going through the links and trying to figure out the connection to 3D Tiles by doing websearches like `companyName "3d tiles"` takes a while...)</sup>

The basic structure consists of several sections, where each section contains a link+screenshot, and a short description. 

The sections _currently_ are

- Generating and Hosting 3D Tiles
- Viewing 3D Tiles
- Data Providers
- Applications and Services Using 3D Tiles
- Developer Tools

Further sections, with information from the RESOURCES.md, could be 

- Articles, Videos, Presentations, and Blog Posts _(and this could be one or four sections...)_
- Demos 

---

This PR is only opened as a **draft**, for early feedback.

### CODE REVIEW

**Comment by lilleyse** [comment]
Here's how I envision the sections and layout of the page. If there's too many screenshots it becomes difficult to parse so I only have screenshots in the Featured Demos section at the bottom. This is essentially the same as "Applications and Services Using 3D Tiles" just with a different name.

## 3D Tiles Resources

* [**Introducing 3D Tiles**](https://cesium.com/blog/2015/08/10/introducing-3d-tiles/) - the motivation for and principles of 3D Tiles.  Read this first if you are new to 3D Tiles.
* [**Introducing 3D Tiles Next, Streaming Geospatial to the Metaverse**](https://cesium.com/blog/2021/11/10/introducing-3d-tiles-next/) - the announcement of 3D Tiles Next specification, summarizing the technical goals and application areas
* [**3D Tiles Reference Card**](./3d-tiles-reference-card.pdf) - an approachable and concise guide to learning about the main concepts in 3D Tiles and designed to help integrate 3D Tiles into runtime engines.
* [**3D Tiles Q&A**](./Q-and-A.md)

**Viewers**

* [Name](link) - description
* [Name](link) - description

**Tools**

* [Name](link) - description
* [Name](link) - description

**Sample Data**

* [Name](link) - description
* [Name](link) - description

**Generators**

* [Name](link) - description
* [Name](link) - description

**Data Providers**

* [Name](link) - description
* [Name](link) - description

**Selected Talks**

   * _Talk name_ ([pdf](link)) at event (Month Year).
   * _Talk name_ ([pdf](link)) at event (Month Year).

**Selected Articles**
   * [Title](link). Month Year.
   * [Title](link). Month Year.

**Featured Demos**

<table>
  <tr>
    <td width="30%"><a href="https://cesium.com/blog/2018/08/21/cybercity/"></a></td>
    <td>Description</td>
  </tr>
  <tr>
    <td width="30%"><a href="https://apps.agi.com/SatelliteViewer/?Status=Operational"></a></td>
    <td>Description</td>
  </tr>
</table>

**Comment by lilleyse** [comment]
And to help seed some of these categories:

**Viewers**
* https://github.com/CesiumGS/cesium
* https://github.com/CesiumGS/cesium-native
* https://github.com/CesiumGS/cesium-unreal
* https://github.com/CesiumGS/cesium-o3de
* https://github.com/NASA-AMMOS/3DTilesRendererJS
* https://github.com/NASA-AMMOS/Unity3DTiles
* https://github.com/visgl/loaders.gl
* https://github.com/ebeaufay/3DTilesViewer
* https://github.com/Geodan/mapbox-3dtiles
* https://github.com/nytimes/three-loader-3dtiles
* TODO: see ecosystem diagram from 2019

**Tools**
* https://github.com/CesiumGS/3d-tiles-validator

**Sample Data**
* https://github.com/CesiumGS/3d-tiles-samples
* https://github.com/NASA-AMMOS/3DTilesSampleData

**Generators**
* Cesium ion
* https://github.com/CesiumGS/cdb-to-3dtiles
* TODO: browse projects in https://github.com/search?q=3D+Tiles
* TODO: see ecosystem diagram from 2019

**Data Providers**
* TODO: see ecosystem diagram from 2019

**Selected Talks**
   * Add 3D Tiles related talks from the [presentations page](https://cesium.com/learn/presentations/)

**Selected Articles**
   * https://eng.uber.com/3d-tiles-loadersgl/
   * Add 3D Tiles related blog posts from the [blog](https://cesium.com/blog)

**Featured Demos**
 * [Photogrammetry Classification Demo](https://demos.cesium.com/ferry-building)
 * [Property Textures Demo](https://demos.cesium.com/owt-uncertainty)
 * [S2 Base Globe Demo](https://demos.cesium.com/owt-globe)
 * [CDB Yemen Demo](https://demos.cesium.com/cdb-yemen)

image
_Ecosystem diagram from 2019_

**Comment by jailln** [comment]
Hi,
Two nice tools working with 3D Tiles to add to the list:
* [itowns](https://github.com/iTowns/itowns) : viewer
* [py3dtilers](https://github.com/VCityTeam/py3dtilers): generator

**Comment by javagl** [comment]
> And to help seed some of these categories:

The current effort is less in "seeding" these categories, but rather in ... "weeding them out" or organizing them in a sensible form. To summarize the suggestion:

- The "Selected Talks" and "Selected Articles" are largely taken from RESOURCES.md as they are (with the given additions)
- The other section will be
   - Viewers
   - Tools
   - Sample Data
   - Generators
   - Data Providers
  
  and the "seeding" should probably refer to giving an idea what should be in each category. But the borders between these categories are certainly blurred. The glTF-Project-Explorer tried to tackle this, _to some extent_ by allowing to specify "tasks": One tool could support the tasks of "view" and "export" if it could visualize and write the data. But this is still far from perfect (c.f. https://github.com/KhronosGroup/glTF-Project-Explorer/issues/111 )

- Deriving **useful** information from a single link (or a logo in an image...), and presenting it in a **useful** way can be difficult, but I'll give it a stab...

---

> Two nice tools working with 3D Tiles to add to the list:

Both of them are already listed in ECOSYSTEM.md. That's one of the things that I referred to when saying that it is difficult to present all this in a useful way....

---

(Eventually, people *will* type `something something 3D Tiles` into Google and hit "I'm feeling lucky". But it still makes sense to have a curated list of resources, and if doing a CTRL+F search on that page leads to the expected result, that could be fine...)

**Comment by jailln** [comment]
> Both of them are already listed in ECOSYSTEM.md. That's one of the things that I referred to when saying that it is difficult to present all this in a useful way....

Oh actually yes for itowns, my bad. Regarding the other one, I mentioned [py3dtileRs](https://github.com/VCityTeam/py3dtilers) (which is based on [py3dtiles](https://gitlab.com/Oslandia/py3dtiles) that is already listed but which is not the same).

I agree with you that the current lists are not so easy to go through. For what it's worth, I like @lilleyse proposition of putting screenshots only for featured demos to ease navigation in these resources.

**Comment by javagl** [comment]
Sorry, I overlooked that 'r'. 

This is also related to some of the questions that are relevant here, and that are discussed in a similar form for the https://github.com/KhronosGroup/glTF-Project-Explorer .

(And again, as a disclaimer: I think it's **good** to at least **have** that resource information, curated, and in one place - everything that I'm talking about here is about details regarding the presentation and structure)

For this example: One can create a list

- [py3dtiles](https://gitlab.com/Oslandia/py3dtiles) - A Python-based implementation of 3D Tiles
- [py3dtilers](https://github.com/VCityTeam/py3dtilers) - A Python-based implementation of a 3D Tiles generator
- ... 

and some of these questions are:

- What is somebody searching for, so that these links provide "The Answer"? (Which is not answered by Googling)
- Who will read a list of ~50 links like this? (It can support CTRL+F in the best case) 
- What will be the order of the list entries? 
  - This is more important that one might think. It refers to the question of whether one tool/library is listed more "prominently" than the other, and conversely, to the effect of prominently linking to a GitHub repo where the last commit was 5 years ago...
- ...

And for each **entry** one can ask more specific questions: 

- In which category/section should `py3dtiles` be? 
- Why do we have to mention that it is "Python-based"? 
  - Why do other entries not say which language it is based on?
- Do people want to know the license of each of these libraries? (The glTF-Project-Explorer has a dedicated `license` tag)
- Do people want to know the _input_ formats that can be processed with `py3dtileRs`?
  - Its README mentions *"**e.g.** OBJ, GeoJSON, IFC or CityGML through 3dCityDB databases"* - what does that mean?
- ... 

---

I already considered to collect all this, in a structure similar to that used by the glTF-Project-Explorer, just to _have_ that information in _a machine-processable form_ in the first place. The reason is simple: Generating a markdown file from such a JSON is trivial. The other way around is impossible. But I'll at least try to create a first page, based on the information from the existing pages for now. Going beyond that wouldn't make much sense due to all the open (and open-ended) questions.

**Comment by javagl** [comment]
A small update with an intermediate state:

I reemoved ECOSYSTEM.md and moved its contents into https://github.com/javagl/3d-tiles/blob/draft-1.1-resources/RESOURCES.md . The ECOSYSTEM.md only contained screenshots+links. These are now _mainly_ listed in the table under _"Applications and Services Using 3D Tiles"_ (which is separate from _"Featured Demos"_). I verified/added these entries insofar that I tried to add a short description of what the use-case is. A few entries have already been moved to other places (e.g. into the _"Generators"_ section), but there still are a few entries that are not really plain _uses_ of 3D Tiles, but could reasonably be considered to be Tools/Generators/Viewers/..., so this still has to be reviewed at some point.

The suggested sections have largely been filled with the suggested links. **But** they may still undergo a few 'refactorings'. For example, I added a section _"Implementations"_. The reason is simply that something like `cesium-native` or `loaders.gl` are not "Viewers". Some of them are plain, direct implementations of the data structures of 3D Tiles. There sometimes are no clear borders between "loaders", "loader plugins", "visualization plugins" and "visualizers", but we'll sort that out at some point...

There are still several TODOs at the bottom of the RESOURCES.md, but I'll address them ASAP.

**Comment by javagl** [comment]
There are still some pending TODOs, which are largely related to adding further entries in each of the current categories:

- Browse projects in https://github.com/search?q=3D+Tiles
- Add entries for ecosystem diagram from 2019
- Add latest presentations from https://cesium.com/learn/presentations/
- Sort these in:
  - [Peaxy](https://peaxy.net/) (Was mentioned in the original ECOSYSTEM.md, without context...)
  - [py3dtiles](https://github.com/Oslandia/py3dtiles)
  - https://github.com/VCityTeam/py3dtilers

A somewhat broader question is how the original "3D Tiles Next Resources" should be weaved in there, or more generally, in how far sections will be to be explicit about whether something refers to 3D Tiles 1.0, Next, or 1.1. 

But for now, I tried to bring the RESOURCES.md into a first, sensible shape so that it could be merged.

**Comment by lilleyse** [comment]
> A somewhat broader question is how the original "3D Tiles Next Resources" should be weaved in there, or more generally, in how far sections will be to be explicit about whether something refers to 3D Tiles 1.0, Next, or 1.1.

I think it's good to be explicit, especially for items in the viewer, implementations, and tools sections.

**Comment by javagl** [comment]
- Updated the presentations section with the links to the presentation page (replacing the broken links to the PDF files). 
- Added the entries that had been mentioned in GitHub comments, and went through the ecosystem diagram and added most of the corresponding entries

The latter has some caveats. The connection between the respective company/product is not always obvious, and sometimes rather tangential. My starting point usually was a webseach for _`<companyName>`_`"3d tiles"`, and/or looking at the company website directly, and the results varied:

- In some cases, there clearly was a viewer/generator/dataset related to 3D Tiles - that's simple
- In some cases, 3D Tiles was vaguely mentioned, like being one of a long list of possible "export formats" or so. I added these as well, hesitatingly
- In some cases, the only connection between the company and 3D Tiles seemed to be one of the Cesium blog posts. I think/hope that these will be covered by the "Selected Articles"
- -In surprisingly many, cases, the only connection seemed to be ... that the company was mentioned in the original `ECOSYSTEM.md`. I omitted some of them. Mentioning a company/product without any obvious connection to 3D Tiles defeats the purpose of this resources page. 

---

An aside: Some of the original entries in the `ECOSYSTEM.md` now appear twice: Once in the table that shows the screenshots, and once in the respective category (Viewer/Generator...). There are clear-cut examples: https://map.geo.admin.ch/ only _uses_ 3D Tiles. It is not a (standalone) viewer or generator. It only shows one use-case. But generally, separating between a "demo/example" and an "application" can be hard.

(In fact, for some of the "demos", I went the extra mile: I opened the demo and looked at the Browser->Network tab to see whether there are requests for a tileset.json or some B3DM going out, to be sure that this is actually 3D Tiles. In some cases, it was rather disappointing to see that demos just plainly do not work (at all), but maybe that's normal nowadays...)

---

Further steps for extending the lists would be to search for https://github.com/search?q=3D+Tiles - but I think that blindly adding further links here does not make much sense. If/when this is tackled, then the information should be condensed in a machine-readable form, _including_ the information of whether a certain project supports 1.0 and/or 1.1, for example.

**Comment by lilleyse** [comment]
@javagl this looks good. I did an edit pass over the document and filled in the talks and articles sections from scanning the Cesium blog and presentations page. I left a couple TODOs for things that will be posted soon. I also removed anything that was marked as discontinued.

Eventually the **Applications and Services Using 3D Tiles** section will need to be filled in since most of the content there is from 2017, but that doesn't have to hold up the PR.

**Comment by lilleyse** [comment]
> I left a couple TODOs for things that will be posted soon.

I decided to remove these TODOs in https://github.com/CesiumGS/3d-tiles/pull/680/commits/ba8cbd1fb5abe694621626e74fde00bb66ca3568 to unblock this PR. They can be added later.

**Pull request merged**
