### PR TITLE
Avoid duplication in schema with metadataEntity

### PR DESCRIPTION
**Pull request by javagl**
A draft that may eventually fix https://github.com/CesiumGS/3d-tiles/issues/607 - further details to be discussed there.

### CODE REVIEW

**Comment by lilleyse** [comment]
This change looks good to me. It's essentially equivalent to what glTF does for [material.normalTextureInfo.schema.json](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.normalTextureInfo.schema.json) and [material.occlusionTextureInfo.schema.json](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.occlusionTextureInfo.schema.json) which "inherit" from `textureInfo.schema.json` and can add their own additional properties. The code generators in cesium-native handle these types.

One difference I noticed is that `material.normalTextureInfo.schema.json` and `material.occlusionTextureInfo.schema.json` declare the properties of the base schema.

```
        "index": { },
        "texCoord": { },
```

Should that be happening here as well?

```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "group.schema.json",
    "title": "Group Metadata",
    "type": "object",
    "description": "An object containing metadata about a group.",
    "allOf": [
        {
            "$ref": "metadataEntity.schema.json"
        }
    ],
    "properties": {
        "class": {},
        "properties": {},
        "extensions": {},
        "extras": {}
    }
}
```

**Comment by javagl** [comment]
> Should that be happening here as well?

This could be done here, and maybe it _should_ be done, but only for consistency. Long(er)-term, these properties may be omitted when they are already mentioned in the `allOf` base schema. (This might eventually also be done in glTF, as of https://github.com/KhronosGroup/glTF/issues/2062#issuecomment-934201170 , but probably only after a few other updates).

**Comment by javagl** [comment]
I could mark this as "ready for review", but before merging, we should probably check whether the spec text should be updated - for example, places that talk about a `group` might have to be reworded, from

> This-and-that is a group, see the `[group.schema.json]`

to 

> A group is a metadata entity, see `[metadataEntity.schema.json]`

**Comment by lilleyse** [comment]
Yes, do a pass over the spec text and then bump me for review.

**Comment by javagl** [comment]
I've added the links to the schema where appropriate, and did a minor wording update. 

I stumbled over the fact that the word 'entity' was apparently used with a meaning that is different from the definition in the https://github.com/CesiumGS/3d-tiles/tree/main/specification/Metadata#concepts section:

> Entities are instantiations of a class, populated with property values conforming to the class definition.

The wording here said

> ... properties do not take on particular values until a metadata is assigned (i.e. the class is "instatiated") to a particular entity within the 3D Tiles hierarchy

Specifically:

- "Entity" once means "that thing that is created from the metadata values" (i.e. the instance of the metadata class)
- "entity" can also be the object that this instance is _associated with_ (e.g. the group or tile)

Maybe the wording would be less confusing if it was

> ... properties do not take on particular values until a metadata is assigned (i.e. the class is "instatiated") to a particular <strike>entity within</strike> **element of** the 3D Tiles hierarchy

but maybe some of these ambiguities are inevietable, due to the genericity of the terms. I hope that the updated wording is OK, though...

**Comment by lilleyse** [comment]
Thanks @javagl. The edits looks good to me.

**Pull request merged**
